### ISSUE TITLE
Update due to "george" library update

### ISSUE THREAD

**Issue by stefanocovino** [RuthAngus/GProtation#20]
Dear Ruth,

I'm playing with the library but I see an error as soon as I try to execute "gprot-fit":

gprot-fit -h
Traceback (most recent call last):
  File "/Users/covino/Pacchetti/anaconda3/bin/gprot-fit", line 4, in <module>
    __import__('pkg_resources').run_script('gprot==0.1', 'gprot-fit')
  File "/Users/covino/Pacchetti/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/covino/Pacchetti/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/Users/covino/Pacchetti/anaconda3/lib/python3.7/site-packages/gprot-0.1-py3.7.egg/EGG-INFO/scripts/gprot-fit", line 10, in <module>
    from gprot.model import GPRotModel, GPRotModel2
  File "/Users/covino/Pacchetti/anaconda3/lib/python3.7/site-packages/gprot-0.1-py3.7.egg/gprot/model.py", line 10, in <module>
    from george.kernels import ExpSine2Kernel, ExpSquaredKernel, WhiteKernel, CosineKernel
ImportError: cannot import name 'WhiteKernel' from 'george.kernels' (/Users/covino/Pacchetti/anaconda3/lib/python3.7/site-packages/george/kernels.py)

I think it is just a change in the "george" library, the WhiteKernel.

Thanks,
   Stefano

**Comment by RuthAngus** [comment]
Hi Stefano, 

Thanks for raising this issue. Unfortunately, I am no longer maintaining this package. If you're interested in using GPs to measure rotation periods, I recommend [celerite](https://celerite.readthedocs.io/en/latest/?badge=latest) or [exoplanet](https://exoplanet.readthedocs.io/en/stable/).
